### ISSUE TITLE
デフォルト都市を東京からハワイに変更してください

### ISSUE THREAD

**Issue by qa-hanayo** [HanayoCorp/meeting-time#48]
@supersunnnny 
@HanayoCorp/team-qa 

### マージ条件
- [ ] テストを通る
- [ ] QA担当者がOKを出す

#45

**Comment by dev-sunny** [comment]
@hanayoQA 了解しました。また連絡します。

**Comment by dev-sunny** [comment]
<img width="217" alt="2016-11-22 13 52 05" src="https://cloud.githubusercontent.com/assets/18607329/20511357/ff6c88d0-b0ba-11e6-9799-87bcab442f38.png">
