### ISSUE TITLE
デフォルト都市の変更

### ISSUE THREAD

**Issue by qa-hanayo** [HanayoCorp/meeting-time#54]
@qa-supersunnnny 
デフォルト都市をハワイから東京に変更してください 👇 
<img width="352" alt="2016-11-22 13 56 36" src="https://cloud.githubusercontent.com/assets/18608088/20511406/87072764-b0bb-11e6-898a-5b27860ba8e8.png">

### マージ条件
- [ ] 自動テストを通ること
- [ ] QA担当がokすること

**Comment by dev-sunny** [comment]
@hanayoQA 了解しました。しばしお待ちください。
