### ISSUE TITLE
デフォルト都市を変更

### ISSUE THREAD

**Issue by qa-hanayo** [HanayoCorp/meeting-time#56]
@dev-sunny 
ハワイから東京に変更してください
![2016-11-22 16 29 33](https://cloud.githubusercontent.com/assets/18608088/20514717/e356d112-b0d0-11e6-8451-bae493986dc0.png)

@HanayoCorp/team-qa 

### マージ条件
- [ ] テストを通ること
- [ ] QA担当がokを出す

**Comment by dev-sunny** [comment]
@qa-hanayo 了解しました。
